packages:
  - docs

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@antfu/ni': ^27.0.1
  '@types/node': ^24.10.0
  '@types/picomatch': ^4.0.2
  ansis: ^4.2.0
  bumpp: ^10.3.1
  bun-types-no-globals: ^1.2.22
  esbuild: ^0.25.12
  eslint: ^9.39.0
  eslint-plugin-format: ^1.0.2
  jiti: ^2.6.1
  lint-staged: ^16.2.6
  simple-git-hooks: ^2.13.1
  tsdown: ^0.15.12
  typescript: ~5.9.3
  unplugin-unused: ^0.5.5

catalogs:
  docs:
    '@iconify-json/ri': ^1.2.6
    '@shikijs/vitepress-twoslash': ^3.14.0
    case-police: ^2.0.0
    consola: ^3.4.2
    dotenv: ^17.2.3
    markdown-it: ^14.1.0
    markdown-it-github-alerts: ^1.0.0
    ofetch: ^1.5.1
    unocss: ^66.5.4
    unplugin-icons: ^22.5.0
    unplugin-vue-components: ^30.0.0
    vitepress: 2.0.0-alpha.10
    vitepress-plugin-group-icons: ^1.6.5
    vue: ^3.5.22
    vue-tsc: ^3.1.3

  peer:
    '@farmfe/core': ^1.7.11
    '@rspack/core': ^1.6.0
    rolldown: ^1.0.0-beta.46
    rollup: ^4.52.5
    unloader: ^0.5.0
    vite: ^7.1.12
    webpack: ^5.102.1

  prod:
    '@jridgewell/remapping': ^2.3.5
    acorn: ^8.15.0
    picomatch: ^4.0.3
    webpack-virtual-modules: ^0.6.2

  test:
    '@farmfe/cli': ^1.0.5
    '@rspack/cli': ^1.6.0
    magic-string: ^0.30.21
    vitest: ^4.0.6
    webpack-cli: ^6.0.1

onlyBuiltDependencies:
  - core-js
  - esbuild
  - simple-git-hooks
