catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - koa@2.16.3
  - rxjs@7.8.2
  - ua-parser-js@1.0.41

packages:
  - docs

catalogs:
  dev:
    '@antfu/eslint-config': ^7.4.3
    '@antfu/ni': ^28.2.0
    '@types/node': ^25.2.3
    '@types/picomatch': ^4.0.2
    '@typescript/native-preview': 7.0.0-dev.20260122.3
    ansis: ^4.2.0
    bumpp: ^10.4.1
    bun-types-no-globals: ^1.3.9
    esbuild: ^0.27.3
    eslint: ^9.39.2
    eslint-plugin-format: ^1.4.0
    jiti: ^2.6.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    tsdown: ^0.20.3
    typescript: ~5.9.3
    unplugin-unused: ^0.5.7

  docs:
    '@iconify-json/ri': ^1.2.10
    '@shikijs/vitepress-twoslash': ^3.22.0
    case-police: ^2.1.1
    consola: ^3.4.2
    dotenv: ^17.3.1
    markdown-it: ^14.1.1
    markdown-it-github-alerts: ^1.0.1
    ofetch: ^1.5.1
    unocss: ^66.6.0
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^31.0.0
    vitepress: 2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.7.1
    vue: ^3.5.28
    vue-tsc: ^3.2.4

  peer:
    '@farmfe/core': ^1.7.11
    '@rspack/core': ^1.7.6
    rolldown: ^1.0.0-rc.4
    rollup: ^4.57.1
    unloader: ^0.8.3
    vite: ^7.3.1
    webpack: ^5.105.2

  prod:
    '@jridgewell/remapping': ^2.3.5
    picomatch: ^4.0.3
    webpack-virtual-modules: ^0.6.2

  test:
    '@farmfe/cli': ^1.0.5
    '@rspack/cli': ^1.7.6
    magic-string: ^0.30.21
    vitest: ^4.0.18
    webpack-cli: ^6.0.1

allowBuilds:
  core-js: false
  esbuild: false
  simple-git-hooks: false
