catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - koa@2.16.3
  - rxjs@7.8.2
  - ua-parser-js@1.0.41

packages:
  - docs

catalog:
  '@antfu/eslint-config': ^7.0.0
  '@antfu/ni': ^28.1.0
  '@types/node': ^25.0.8
  '@types/picomatch': ^4.0.2
  '@typescript/native-preview': 7.0.0-dev.20260113.1
  ansis: ^4.2.0
  bumpp: ^10.4.0
  bun-types-no-globals: ^1.3.4
  esbuild: ^0.27.2
  eslint: ^9.39.2
  eslint-plugin-format: ^1.3.0
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  simple-git-hooks: ^2.13.1
  tsdown: ^0.20.0-beta.2
  typescript: ~5.9.3
  unplugin-unused: ^0.5.6

catalogs:
  docs:
    '@iconify-json/ri': ^1.2.7
    '@shikijs/vitepress-twoslash': ^3.21.0
    case-police: ^2.1.1
    consola: ^3.4.2
    dotenv: ^17.2.3
    markdown-it: ^14.1.0
    markdown-it-github-alerts: ^1.0.0
    ofetch: ^1.5.1
    unocss: ^66.5.12
    unplugin-icons: ^23.0.0
    unplugin-vue-components: ^31.0.0
    vitepress: 2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.6.5
    vue: ^3.5.26
    vue-tsc: ^3.2.2

  peer:
    '@farmfe/core': ^1.7.11
    '@rspack/core': ^1.7.3
    rolldown: ^1.0.0-beta.59
    rollup: ^4.55.1
    unloader: ^0.8.3
    vite: ^7.3.1
    webpack: ^5.104.1

  prod:
    '@jridgewell/remapping': ^2.3.5
    picomatch: ^4.0.3
    webpack-virtual-modules: ^0.6.2

  test:
    '@farmfe/cli': ^1.0.5
    '@rspack/cli': ^1.7.3
    magic-string: ^0.30.21
    vitest: ^4.0.17
    webpack-cli: ^6.0.1

allowBuilds:
  core-js: false
  esbuild: false
  simple-git-hooks: false
