packages:
  - docs

catalog:
  '@antfu/eslint-config': ^5.2.2
  '@antfu/ni': ^25.0.0
  '@farmfe/cli': ^1.0.5
  '@farmfe/core': ^1.7.11
  '@rspack/cli': ^1.5.0
  '@rspack/core': ^1.5.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.3.1
  '@types/picomatch': ^4.0.2
  ansis: ^4.1.0
  bumpp: ^10.2.3
  esbuild: ^0.25.9
  esbuild-plugin-copy: ^2.1.1
  eslint: ^9.35.0
  eslint-plugin-format: ^1.0.1
  fast-glob: ^3.3.3
  fs-extra: ^11.3.1
  jiti: ^2.5.1
  lint-staged: ^16.1.6
  magic-string: ^0.30.18
  rolldown: ^1.0.0-beta.35
  rollup: ^4.50.0
  simple-git-hooks: ^2.13.1
  tsdown: ^0.14.2
  typescript: ~5.9.2
  unloader: ^0.5.0
  unplugin-unused: ^0.5.2
  vite: ^7.1.4
  vitest: ^3.2.4
  webpack: ^5.101.3
  webpack-cli: ^6.0.1

catalogs:
  docs:
    '@iconify-json/ri': ^1.2.5
    '@shikijs/vitepress-twoslash': ^3.12.2
    case-police: ^2.0.0
    consola: ^3.4.2
    dotenv: ^17.2.2
    markdown-it: ^14.1.0
    markdown-it-github-alerts: ^1.0.0
    ofetch: ^1.4.1
    tsx: ^4.20.5
    unocss: ^66.5.0
    unplugin-icons: ^22.2.0
    unplugin-vue-components: ^29.0.0
    vitepress: 2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.3
    vue: ^3.5.21
    vue-tsc: ^3.0.6

  prod:
    '@jridgewell/remapping': ^2.3.5
    acorn: ^8.15.0
    picomatch: ^4.0.3
    webpack-virtual-modules: ^0.6.2
