ignoreWorkspaceRootCheck: true
catalogMode: prefer
minimumReleaseAge: 0
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
shellEmulator: true

packages:
  - docs

allowBuilds:
  core-js: false
  esbuild: false
  simple-git-hooks: true

catalogs:
  dev:
    '@antfu/eslint-config': ^9.5.1
    '@antfu/ni': ^30.6.0
    '@arethetypeswrong/core': ^0.18.5
    '@types/node': ^26.4.1
    '@types/picomatch': ^4.0.3
    '@typescript/native-preview': 7.0.0-dev.20260707.2
    ansis: ^4.4.0
    bumpp: ^12.3.0
    eslint: ^10.10.0
    eslint-plugin-format: ^2.0.1
    lint-staged: ^17.5.1
    publint: ^0.3.24
    simple-git-hooks: ^2.14.0
    tsdown: ^0.23.0
    typescript: ~6.0.3
    unplugin-unused: ^0.6.0

  docs:
    '@iconify-json/ri': ^1.2.10
    '@shikijs/vitepress-twoslash': ^4.4.3
    case-police: ^2.2.1
    consola: ^3.4.2
    markdown-it: ^15.0.2
    markdown-it-github-alerts: ^1.0.1
    ofetch: ^1.5.1
    unocss: ^66.10.4
    unplugin-icons: ^24.0.0
    unplugin-vue-components: ^32.1.0
    vitepress: 2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.7.6
    vue: ^3.5.42
    vue-tsc: ^3.3.11

  peer:
    '@farmfe/core': ^1.7.11
    '@rsbuild/core': ^2.2.7
    '@rspack/core': ^2.2.5
    bun-types-no-globals: ^1.4.2
    esbuild: ^0.28.2
    rolldown: ^1.2.8
    rollup: ^4.63.3
    unloader: ^0.10.1
    vite: ^8.3.0
    webpack: ^5.111.0

  prod:
    '@jridgewell/remapping': ^2.3.5
    picomatch: ^4.0.7
    webpack-virtual-modules: ^0.6.2

  test:
    '@farmfe/cli': ^1.0.5
    '@rspack/cli': ^2.2.5
    magic-string: ^1.4.1
    vitest: ^5.0.1
    webpack-cli: ^7.2.3
