catalogMode: prefer
ignoreWorkspaceRootCheck: true
minimumReleaseAge: 0
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
trustPolicyExclude:
  - ua-parser-js@1.0.41

packages:
  - docs

catalogs:
  dev:
    '@antfu/eslint-config': ^9.2.0
    '@antfu/ni': ^30.3.0
    '@arethetypeswrong/core': ^0.18.5
    '@types/node': ^26.1.1
    '@types/picomatch': ^4.0.3
    ansis: ^4.3.1
    bumpp: ^12.0.0
    eslint: ^10.8.0
    eslint-plugin-format: ^2.0.1
    jiti: ^2.7.0
    lint-staged: ^17.2.0
    publint: ^0.3.22
    simple-git-hooks: ^2.13.1
    tsdown: ^0.22.14
    typescript: ~6.0.3
    typescript-7: npm:typescript@~7.0.2
    unplugin-unused: ^0.6.0

  docs:
    '@iconify-json/ri': ^1.2.10
    '@shikijs/vitepress-twoslash': ^4.3.1
    case-police: ^2.2.1
    consola: ^3.4.2
    markdown-it: ^14.3.0
    markdown-it-github-alerts: ^1.0.1
    ofetch: ^1.5.1
    unocss: ^66.7.5
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^32.1.0
    vitepress: 2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.7.5
    vue: ^3.5.40
    vue-tsc: ^3.3.8

  peer:
    '@farmfe/core': ^1.7.11
    '@rsbuild/core': ^2.1.8
    '@rspack/core': ^2.1.5
    bun-types-no-globals: ^1.3.11
    esbuild: ^0.28.1
    rolldown: ^1.2.0
    rollup: ^4.62.3
    unloader: ^0.10.0
    vite: ^8.1.5
    webpack: ^5.109.0

  prod:
    '@jridgewell/remapping': ^2.3.5
    picomatch: ^4.0.5
    webpack-virtual-modules: ^0.6.2

  test:
    '@farmfe/cli': ^1.0.5
    '@rspack/cli': ^2.1.5
    magic-string: ^1.1.0
    vitest: ^4.1.10
    webpack-cli: ^7.2.1

allowBuilds:
  core-js: false
  esbuild: false
  simple-git-hooks: false
