name: ci

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:
    branches:
      - main
      - 'v*'

permissions: {}

jobs:
  unit-test:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@main
    with:
      typecheck: pnpm run build && pnpm run typecheck

  unit-test-bun:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@main

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest

      - name: Build
        run: pnpm run build

      - name: Test with bun
        run: bun run scripts/buildFixtures.ts && bun -b vitest --allowOnly
